name = "sb21_surrogate"
uuid = "0e921d4c-edff-46ec-ae31-e277f0125084"
authors = ["Philipsite <philip.hartmeier@hotmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
CUDA = "5.8.3"
CairoMakie = "0.15.6"
DataFrames = "1.7.1"
Dates = "1.11.0"
Flux = "0.16.5"
JLD2 = "0.6.2"
ProgressBars = "1.5.1"
Statistics = "1.11.1"
cuDNN = "1.4.5"
