name = "mp"
oxides = ["SiO2", "Al2O3", "CaO", "MgO", "FeO", "K2O", "Na2O", "TiO2", "O", "MnO", "H2O"]
database = "Metapelite (White et al., 2014)"

[pure_phases]
names = ["q", "crst", "trd", "coe", "stv", "ky", "sill", "and", "ru", "sph", "O2", "H2O", "zo"]

    [pure_phases.composition]
    ru = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    zo = [3.0, 1.5, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
    trd = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    coe = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    and = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    q = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    crst = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    O2 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0]
    sill = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    stv = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    sph = [1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    H2O = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
    ky = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[solution_phases]
names = ["liq", "fsp", "bi", "g", "ep", "ma", "mu", "opx", "sa", "cd", "st", "chl", "ctd", "sp", "mt", "ilm", "ilmm"]

    [solution_phases.data.cd]
    endmembers = ["crd", "fcrd", "hcrd", "mncd"]
    site_fractions = ["xFeX", "xMgX", "xMnX", "xH2OH", "xvH"]

        [solution_phases.data.cd.composition]
        crd = [5.0, 2.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        mncd = [5.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        fcrd = [5.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        hcrd = [5.0, 2.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    [solution_phases.data.fsp]
    endmembers = ["ab", "an", "san"]
    site_fractions = ["xNaA", "xCaA", "xKA", "xAlTB", "xSiTB"]

        [solution_phases.data.fsp.composition]
        san = [3.0, 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0]
        ab = [3.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0]
        an = [2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    [solution_phases.data.ma]
    endmembers = ["mut", "celt", "fcelt", "pat", "ma", "fmu"]
    site_fractions = ["xKA", "xNaA", "xCaA", "xMgM2A", "xFeM2A", "xAlM2A", "xAlM2B", "xFe3M2B", "xSiT1", "xAlT1"]

        [solution_phases.data.ma.composition]
        fmu = [3.0, 1.0, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 0.5, 0.0, 1.0]
        fcelt = [4.0, 0.5, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        celt = [4.0, 0.5, 0.0, 1.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        ma = [2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        mut = [3.0, 1.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        pat = [3.0, 1.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 1.0]

    [solution_phases.data.mu]
    endmembers = ["mut", "cel", "fcel", "pat", "ma", "fmu"]
    site_fractions = ["xKA", "xNaA", "xCaA", "xMgM2A", "xFeM2A", "xAlM2A", "xAlM2B", "xFe3M2B", "xSiT1", "xAlT1"]

        [solution_phases.data.mu.composition]
        fmu = [3.0, 1.0, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 0.5, 0.0, 1.0]
        fcel = [4.0, 0.5, 0.0, 0.0, 1.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        ma = [2.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        mut = [3.0, 1.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        pat = [3.0, 1.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 1.0]
        cel = [4.0, 0.5, 0.0, 1.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]

    [solution_phases.data.opx]
    endmembers = ["en", "fs", "fm", "mgts", "fopx", "mnopx", "odi"]
    site_fractions = ["xMgM1", "xFeM1", "xMnM1", "xFe3M1", "xAlM1", "xMgM2", "xFeM2", "xMnM2", "xCaM2", "xSiT", "xAlT"]

        [solution_phases.data.opx.composition]
        fs = [2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        fm = [2.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        mnopx = [2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        mgts = [1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        en = [2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        odi = [2.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        fopx = [1.0, 0.5, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0]

    [solution_phases.data.ctd]
    endmembers = ["mctd", "fctd", "mnct", "ctdo"]
    site_fractions = ["xAlM1A", "xFe3M1A", "xFeM1B", "xMgM1B", "xMnM1B"]

        [solution_phases.data.ctd.composition]
        mctd = [1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        ctdo = [1.0, 0.75, 0.0, 1.0, 0.5, 0.0, 0.0, 0.0, 0.25, 0.0, 1.0]
        fctd = [1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        mnct = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0]

    [solution_phases.data.ep]
    endmembers = ["cz", "ep", "fep"]
    site_fractions = ["xFeM1", "xAlM1", "xFeM3", "xAlM3"]

        [solution_phases.data.ep.composition]
        cz = [3.0, 1.5, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5]
        ep = [3.0, 1.0, 2.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5]
        fep = [3.0, 0.5, 2.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.5]

    [solution_phases.data.st]
    endmembers = ["mstm", "fst", "mnstm", "msto", "mstt"]
    site_fractions = ["xMgX", "xFeX", "xMnX", "xAlY", "xFe3Y", "xTiY", "xvY"]

        [solution_phases.data.st.composition]
        mstt = [7.5, 8.0, 0.0, 4.0, 0.0, 0.0, 0.0, 1.5, 0.0, 0.0, 2.0]
        mstm = [7.5, 9.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0]
        msto = [7.5, 8.0, 0.0, 4.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0]
        mnstm = [7.5, 9.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 2.0]
        fst = [7.5, 9.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0]

    [solution_phases.data.mt]
    endmembers = ["imt", "dmt", "usp"]
    site_fractions = ["xTiM", "xFe3M", "xFeM", "xFe3T", "xFeT"]

        [solution_phases.data.mt.composition]
        dmt = [0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
        imt = [0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
        usp = [0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

    [solution_phases.data.ilmm]
    endmembers = ["oilm", "dilm", "dhem", "geik", "pnt"]
    site_fractions = ["xFeA", "xTiA", "xMgA", "xMnA", "xFe3A", "xFeB", "xTiB"]

        [solution_phases.data.ilmm.composition]
        oilm = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        geik = [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        dilm = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        dhem = [0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
        pnt = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0]

    [solution_phases.data.g]
    endmembers = ["py", "alm", "spss", "gr", "kho"]
    site_fractions = ["xMgX", "xFeX", "xMnX", "xCaX", "xAlY", "xFe3Y"]

        [solution_phases.data.g.composition]
        spss = [3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0]
        alm = [3.0, 1.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        gr = [3.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        py = [3.0, 1.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        kho = [3.0, 0.0, 0.0, 3.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]

    [solution_phases.data.sp]
    endmembers = ["herc", "sp", "mt", "usp"]
    site_fractions = ["xAl", "xFe3", "xTi", "xMg", "xFe2"]

        [solution_phases.data.sp.composition]
        sp = [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        mt = [0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
        herc = [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        usp = [0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

    [solution_phases.data.liq]
    endmembers = ["q4L", "abL", "kspL", "anL", "slL", "fo2L", "fa2L", "h2oL"]
    site_fractions = ["fac", "pq", "xab", "xksp", "pan", "psil", "pol", "xFe", "xMg", "ph2o"]

        [solution_phases.data.liq.composition]
        q4L = [4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        abL = [3.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0]
        fa2L = [2.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        h2oL = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        slL = [1.6, 1.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        anL = [2.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        kspL = [3.0, 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0]
        fo2L = [2.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    [solution_phases.data.ilm]
    endmembers = ["oilm", "dilm", "dhem"]
    site_fractions = ["xFe2A", "xTiA", "xFe3A", "xFe2B", "xTiB", "xFe3B"]

        [solution_phases.data.ilm.composition]
        oilm = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        dilm = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        dhem = [0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]

    [solution_phases.data.bi]
    endmembers = ["phl", "annm", "obi", "east", "tbi", "fbi", "mmbi"]
    site_fractions = ["xMgM3", "xMnM3", "xFeM3", "xFe3M3", "xTiM3", "xAlM3", "xMgM12", "xMnM12", "xFeM12", "xSiT", "xAlT", "xOHV", "xOV"]

        [solution_phases.data.bi.composition]
        obi = [3.0, 0.5, 0.0, 2.0, 1.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        east = [2.0, 1.5, 0.0, 2.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        tbi = [3.0, 0.5, 0.0, 2.0, 0.0, 0.5, 0.0, 1.0, 0.0, 0.0, 0.0]
        mmbi = [3.0, 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 3.0, 1.0]
        annm = [3.0, 0.5, 0.0, 0.0, 3.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        phl = [3.0, 0.5, 0.0, 3.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 1.0]
        fbi = [2.0, 1.0, 0.0, 2.0, 1.0, 0.5, 0.0, 0.0, 0.5, 0.0, 1.0]

    [solution_phases.data.chl]
    endmembers = ["clin", "afchl", "ames", "daph", "ochl1", "ochl4", "f3clin", "mmchl"]
    site_fractions = ["xMgM1", "xMnM1", "xFeM1", "xAlM1", "xMgM23", "xFeM23", "xMgM4", "xFeM4", "xFe3M4", "xAlM4", "xSiT2", "xAlT2"]

        [solution_phases.data.chl.composition]
        f3clin = [3.0, 0.5, 0.0, 5.0, 1.0, 0.0, 0.0, 0.0, 0.5, 0.0, 4.0]
        mmchl = [3.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0, 4.0]
        daph = [3.0, 1.0, 0.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]
        clin = [3.0, 1.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]
        ames = [2.0, 2.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]
        ochl1 = [4.0, 0.0, 0.0, 1.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]
        ochl4 = [4.0, 0.0, 0.0, 5.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]
        afchl = [4.0, 0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0]

    [solution_phases.data.sa]
    endmembers = ["spr4", "spr5", "fspm", "spro", "ospr"]
    site_fractions = ["xMgM3", "xFeM3", "xFe3M3", "xAlM3", "xMgM456", "xFeM456", "xSiT", "xAlT"]

        [solution_phases.data.sa.composition]
        ospr = [1.0, 4.5, 0.0, 3.0, 1.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0]
        spro = [2.0, 4.0, 0.0, 1.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        spr4 = [2.0, 4.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        spr5 = [1.0, 5.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        fspm = [2.0, 4.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
