name = "sb21"
oxides = ["SiO2", "CaO", "Al2O3", "FeO", "MgO", "Na2O"]
database = "Stixrude & Lithgow-Bertelloni (2021)"

[pure_phases]
names = ["neph", "ky", "st", "coe", "qtz", "capv", "co"]

    [pure_phases.composition]
    st = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    capv = [1.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    neph = [1.0, 0.0, 0.5, 0.0, 0.0, 0.5]
    qtz = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    co = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    ky = [1.0, 0.0, 1.0, 0.0, 0.0, 0.0]
    coe = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[solution_phases]
names = ["plg", "sp", "ol", "wa", "ri", "opx", "cpx", "hpcpx", "ak", "gtmj", "pv", "ppv", "cf", "mw", "nal"]

    [solution_phases.data.nal]
    endmembers = ["mnal", "fnal", "nnal"]
    site_fractions = ["", "", ""]

        [solution_phases.data.nal.composition]
        nnal = [3.0, 0.0, 1.5, 0.0, 0.0, 1.5]
        mnal = [1.0, 0.0, 2.5, 0.0, 2.0, 0.5]
        fnal = [1.0, 0.0, 2.5, 2.0, 0.0, 0.5]

    [solution_phases.data.plg]
    endmembers = ["an", "ab"]
    site_fractions = [""]

        [solution_phases.data.plg.composition]
        ab = [3.0, 0.0, 0.5, 0.0, 0.0, 0.5]
        an = [2.0, 1.0, 1.0, 0.0, 0.0, 0.0]

    [solution_phases.data.opx]
    endmembers = ["en", "fs", "mgts", "odi"]
    site_fractions = ["", ""]

        [solution_phases.data.opx.composition]
        fs = [2.0, 0.0, 0.0, 2.0, 0.0, 0.0]
        mgts = [1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
        en = [2.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        odi = [2.0, 1.0, 0.0, 0.0, 1.0, 0.0]

    [solution_phases.data.pv]
    endmembers = ["mgpv", "fepv", "alpv"]
    site_fractions = ["", ""]

        [solution_phases.data.pv.composition]
        mgpv = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
        alpv = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        fepv = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0]

    [solution_phases.data.wa]
    endmembers = ["mgwa", "fewa"]
    site_fractions = [""]

        [solution_phases.data.wa.composition]
        fewa = [1.0, 0.0, 0.0, 2.0, 0.0, 0.0]
        mgwa = [1.0, 0.0, 0.0, 0.0, 2.0, 0.0]

    [solution_phases.data.ri]
    endmembers = ["mgri", "feri"]
    site_fractions = [""]

        [solution_phases.data.ri.composition]
        feri = [1.0, 0.0, 0.0, 2.0, 0.0, 0.0]
        mgri = [1.0, 0.0, 0.0, 0.0, 2.0, 0.0]

    [solution_phases.data.gtmj]
    endmembers = ["py", "alm", "gr", "mgmj", "jdmj"]
    site_fractions = ["", "", ""]

        [solution_phases.data.gtmj.composition]
        alm = [3.0, 0.0, 1.0, 3.0, 0.0, 0.0]
        gr = [3.0, 3.0, 1.0, 0.0, 0.0, 0.0]
        py = [3.0, 0.0, 1.0, 0.0, 3.0, 0.0]
        jdmj = [5.0, 0.0, 0.0, 0.0, 1.0, 1.0]
        mgmj = [4.0, 0.0, 0.0, 0.0, 4.0, 0.0]

    [solution_phases.data.sp]
    endmembers = ["sp", "hc"]
    site_fractions = ["", ""]

        [solution_phases.data.sp.composition]
        sp = [0.0, 0.0, 4.0, 0.0, 4.0, 0.0]
        hc = [0.0, 0.0, 4.0, 4.0, 0.0, 0.0]

    [solution_phases.data.mw]
    endmembers = ["pe", "wu", "anao"]
    site_fractions = ["", ""]

        [solution_phases.data.mw.composition]
        pe = [0.0, 0.0, 0.0, 0.0, 4.0, 0.0]
        wu = [0.0, 0.0, 0.0, 4.0, 0.0, 0.0]
        anao = [0.0, 0.0, 1.0, 0.0, 0.0, 1.0]

    [solution_phases.data.cpx]
    endmembers = ["di", "he", "cen", "cats", "jd"]
    site_fractions = ["", "", ""]

        [solution_phases.data.cpx.composition]
        jd = [2.0, 0.0, 0.5, 0.0, 0.0, 0.5]
        cen = [2.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        he = [2.0, 1.0, 0.0, 1.0, 0.0, 0.0]
        di = [2.0, 1.0, 0.0, 0.0, 1.0, 0.0]
        cats = [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]

    [solution_phases.data.ak]
    endmembers = ["mgak", "feak", "co"]
    site_fractions = ["", ""]

        [solution_phases.data.ak.composition]
        mgak = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
        feak = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
        co = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]

    [solution_phases.data.ol]
    endmembers = ["fo", "fa"]
    site_fractions = [""]

        [solution_phases.data.ol.composition]
        fo = [1.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        fa = [1.0, 0.0, 0.0, 2.0, 0.0, 0.0]

    [solution_phases.data.cf]
    endmembers = ["mgcf", "fecf", "nacf"]
    site_fractions = ["", ""]

        [solution_phases.data.cf.composition]
        mgcf = [0.0, 0.0, 1.0, 0.0, 1.0, 0.0]
        fecf = [0.0, 0.0, 1.0, 1.0, 0.0, 0.0]
        nacf = [1.0, 0.0, 0.5, 0.0, 0.0, 0.5]

    [solution_phases.data.hpcpx]
    endmembers = ["hpcen", "hpcfs"]
    site_fractions = [""]

        [solution_phases.data.hpcpx.composition]
        hpcen = [2.0, 0.0, 0.0, 0.0, 2.0, 0.0]
        hpcfs = [2.0, 0.0, 0.0, 2.0, 0.0, 0.0]

    [solution_phases.data.ppv]
    endmembers = ["mppv", "fppv", "appv"]
    site_fractions = ["", ""]

        [solution_phases.data.ppv.composition]
        appv = [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
        mppv = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
        fppv = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
